# Generated by Django 5.2.7 on 2025-10-13 10:03

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('products', '0002_product_disc_product_net_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default='TEMP-SKU-0001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=14, max_length=14, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attributes.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='variants', to='attributes.attributevalue'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
    ]
