# Generated by Django 5.2.7 on 2025-11-04 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('attributes', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='variants', to='attributes.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariantattributemedia',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_media', to='attributes.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariantattributemedia',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='attribute_value_media', to='assets.productimage'),
        ),
        migrations.AddField(
            model_name='productvariantattributemedia',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_media', to='attributes.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattributemedia',
            unique_together={('variant', 'attribute_value')},
        ),
    ]
