# Generated by Django 5.2.7 on 2025-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
