# Generated by Django 5.2.7 on 2025-10-16 19:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('attributes', '0004_productvariant_discount_productvariant_net'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttributeMedia',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False, unique=True)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_media', to='attributes.attributevalue')),
                ('images', models.ManyToManyField(related_name='attribute_value_media', to='assets.productimage')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_media', to='attributes.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'attribute_value')},
            },
        ),
    ]
