# Generated by Django 5.2.7 on 2025-10-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('attributes', '0005_productvariantattributemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattributemedia',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='attribute_value_media', to='assets.productimage'),
        ),
    ]
