# Generated by Django 5.2.7 on 2025-11-04 08:25

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_uuid', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', editable=False, length=10, max_length=14, prefix='LVL-', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_uuid', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', editable=False, length=12, max_length=16, prefix='SEC-', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('carousel', 'Carousel'), ('grid', 'Grid'), ('video', 'Video'), ('filter', 'Filter'), ('deals', 'Deals')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='homepage.homepagelevel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', editable=False, length=14, max_length=18, prefix='ITM-', unique=True)),
                ('image', models.ImageField(upload_to='homepage/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homepage.homepagesection')),
            ],
        ),
    ]
