# Generated by Django 5.2.7 on 2025-12-11 22:30

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='image',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to='homepage/'),
        ),
    ]
