# Generated by Django 5.2.7 on 2025-11-04 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attributes.productvariant'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='attributes.productvariant'),
        ),
    ]
