# Generated by Django 5.2.7 on 2025-12-11 07:40

import core.image_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[core.image_service.utils.validate_image]),
        ),
    ]
