# Generated by Django 5.2.7 on 2025-11-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0002_initial'),
        ('assets', '0002_initial'),
        ('attributes', '0003_alter_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ProductSpecification.productspecification'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attributes.productvariant'),
        ),
    ]
