# Generated by Django 5.2.7 on 2025-11-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0003_productspecificationcontent_and_more'),
        ('assets', '0003_productimage_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='specification',
        ),
        migrations.AddField(
            model_name='productimage',
            name='spec_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ProductSpecification.productspecificationcontent'),
        ),
    ]
