# Generated by Django 5.2.7 on 2025-12-11 07:43

import backend.storage_backends
import core.image_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to='products/', validators=[core.image_service.utils.validate_image]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(storage=backend.storage_backends.MediaStorage(), upload_to='uploads/products/videos/'),
        ),
    ]
