# Generated by Django 5.2.7 on 2025-12-11 23:14

import assets.models
import backend.storage_backends
import core.image_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_productimage_content_type_productimage_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to=assets.models.review_image_upload_path, validators=[core.image_service.utils.validate_image]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(storage=backend.storage_backends.MediaStorage(), upload_to=assets.models.review_video_upload_path),
        ),
    ]
