# Generated by Django 5.2.7 on 2025-10-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Price after discount', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original price', max_digits=10),
        ),
    ]
