# Generated by Django 5.2.7 on 2025-11-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('VERIFY', 'Verify Account'), ('RESET', 'Reset Password')], max_length=10),
        ),
    ]
