# Generated by Django 5.2.7 on 2025-12-14 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlyviewed',
            options={},
        ),
        migrations.AlterField(
            model_name='recentlyviewed',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['user', '-viewed_at'], name='recommendat_user_id_0b2e71_idx'),
        ),
    ]
