# Generated by Django 5.2.7 on 2025-10-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0001_initial'),
        ('products', '0002_product_disc_product_net_alter_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('is_global', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('key', 'value')},
            },
        ),
        migrations.AddField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_links', to='ProductSpecification.specification'),
        ),
    ]
