# Generated by Django 5.2.7 on 2025-10-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0002_alter_productspecification_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='specification',
        ),
    ]
