# Generated by Django 5.2.7 on 2025-10-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0003_remove_productspecification_specification'),
        ('products', '0002_product_disc_product_net_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product'),
        ),
    ]
