# Generated by Django 5.2.7 on 2025-11-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSpecification', '0003_productspecificationcontent_and_more'),
        ('assets', '0004_remove_productimage_specification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
