# Generated by Django 5.2.7 on 2025-12-14 17:07

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.MediaStorage(), upload_to='brand_logos/'),
        ),
    ]
