# Generated by Django 5.2.7 on 2025-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
