# Generated by Django 5.2.7 on 2025-11-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_userprofile_country_userprofile_locale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
